import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../../devlink/global.css";
import { DevLinkProvider } from "../../devlink/DevLinkProvider";
import { MemberstackProvider } from "../components/MemberstackProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
        style={{ fontFamily: 'var(--font-inter)' }}
      >
        <MemberstackProvider>
          <DevLinkProvider>{children}</DevLinkProvider>
        </MemberstackProvider>
      </body>
    </html>
  );
}
